DROP TABLE IF EXISTS REGISTERED_CUSTOMERS; 
CREATE TABLE REGISTERED_CUSTOMERS (
		PASSWORD VARCHAR(256) NOT NULL, 
		EMAIL VARCHAR(50) NOT NULL PRIMARY KEY, 
		FIRST_NAME VARCHAR(20), 
		LAST_NAME VARCHAR(20),
		SALT BLOB(50)
);